### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by zachriggle** [IOActive/jdwp-shellifier#6]
I would like to borrow some of your code, but there's no LICENSE permitting me to do so.

If you wouldn't mind releasing this project with an open-source license, I'd suggest the MIT license.

You can find more info here: http://choosealicense.com/

Thanks, @hugsy!

**Comment by hugsy** [comment]
Hey @zachriggle ,

Thanks for the report, that's a major mistake, fixing it right now.

**Comment by hugsy** [comment]
Fixed by commit e82ec26: code is covered by MIT license.
